### PR TITLE
Makes MRS blast support pyrrolysine residues in a sequence

### PR DESCRIPTION
**Pull request by cbaakman**
Treat pyrrolysine(O) and selenocysteine(U) as X, unless it's a U vs. U or O vs. O match.

### CODE REVIEW

**Comment by cbaakman** [comment]
There is a commandline option ```mrs blast```, the results look normal. Do you mean a unit test?

**Comment by jonblack** [comment]
Yes, I mean a unit test. It's always good to have an automated test for changes. Is this possible?

**Comment by cbaakman** [comment]
It is, once I find out how to make unit tests for c++ code.

**Comment by cbaakman** [comment]
https://github.com/cbaakman/mrs/commit/278b841ee17e0434e8cc484cf043f41422b2949a adds a unit test

**Pull request closed without merging**
